### ISSUE TITLE
Post event announcements to the relevant Slack rooms

### ISSUE THREAD

**Issue by danielthepope** [jsoxford/hubot#38]
At the moment, whenever Dobot detects a new Meetup event with any of the Digital Oxford Meetup groups, it posts a notification in the #Events channel.
Now that we have meetup-groups.json, it should be easy enough to get Dobot to post to the right slack channel.
The response from the API call comes back with the Group ID, which we can match up with the relevant object in meetup-groups.json. If we add a 'slack_channel' field to each object, Dobot can post to the specified room (if it is defined).

I'll probably have a go at this on Saturday, unless someone else wants to jump in beforehand.

**Comment by AverageMarcus** [comment]
Just remember that dobot needs to be invited into that room to post to it. I've gone through and added it to a bunch of rooms already but not all.

**Comment by danielthepope** [comment]
Doing this now. There are some meetup groups which don't have their channel, so Dobot will still post those announcements into #events.

But what do we want to do with something like JSOxford? I'm thinking Dobot should post into both #events and #jsoxford. Any other thoughts?
