### ISSUE TITLE
Idea: pasted Meetup information

### ISSUE THREAD

**Issue by danielthepope** [jsoxford/hubot#51]
![image](https://cloud.githubusercontent.com/assets/5173183/19560952/8cdff924-96ce-11e6-81db-3e87ee9a35fa.png)

In order to get further information about a particular meetup, I _could_ just click on the link.

But I'm very lazy. Instead, how about Dobot queries the Meetup API using the event ID in the link, then says something like `That meetup is "marlow[dev] #5: VR/AR Talks and Tech", at Marlow Rowing Club, on the 2nd November 2016 at 7pm.`

Could be triggered with something like `robot.hear(/meetup\.com\/.*\/events\/(\d+)/)`

Perhaps add to `meetup.js`?

**Comment by AverageMarcus** [comment]
Its such a shame that meetup.com doesn't make this information available to the unfurling. Seems like a good idea to me.

**Comment by danielthepope** [comment]
Looking at this one tonight.
