### ISSUE TITLE
Read Digitaloxford job feed and post to #jobs

### ISSUE THREAD

**Issue by danielthepope** [jsoxford/hubot#52]

**Comment by AverageMarcus** [comment]
I pinged @benfoxall about this on slack earlier. Can be easily done with the RSS feed integration.

**Comment by danielthepope** [comment]
Ah, so not a Dobot thing. That makes sense!

**Comment by AverageMarcus** [comment]
Yeah, no point adding it to dobot while we already have the feed integration.

**Comment by benfoxall** [comment]
👍 Added

(you might be able to do it too with the `/feed` command)
