### ISSUE TITLE
Fix #meetup-buddies channel link in event announcement

### ISSUE THREAD

**Issue by henrahmagix** [jsoxford/hubot#60]
#58 and #59 haven't worked :<

https://digitaloxford.slack.com/archives/events/p1486566411000076
![image](https://cloud.githubusercontent.com/assets/1429026/22743153/3fcc1ea2-ee11-11e6-92d3-c4e81f530d76.png)

**Comment by henrahmagix** [comment]
Seems like the `link_names=1` or `parse=full` modes would work here.

The `Why not join <#C024BE7LR|general>?` part is confusing: I've no idea where to get the ID bit in the first part of `<|>`.

**Comment by omgmog** [comment]
They helpfully output this in the markup on Slack:
![screen shot 2017-02-08 at 15 24 08](https://cloud.githubusercontent.com/assets/50949/22743648/b04a6f98-ee12-11e6-8b51-b4d73d7b81b1.png)

**Comment by omgmog** [comment]
or paste the following in your address bar while the channel you want the ID for is open:

```
javascript:alert($('.channel.active .channel_name').data('channel-id'));
```

**Comment by henrahmagix** [comment]
What if I use the Mac App? =D

**Comment by omgmog** [comment]
Open this in your browser
> https://digitaloxford.slack.com/messages/general/

![](https://media.giphy.com/media/ObqlMo2Iqrp7y/giphy.gif)
