### ISSUE TITLE
Handle recurring meetups

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/hubot#84]
When a recurring meetup is added all the events are announced at once.

![ezgif com-resize](https://user-images.githubusercontent.com/3384072/36780150-07229cc4-1c6a-11e8-9bdd-4b7836295559.gif)

It'd be nice if these could be announced individually after each previous event has passed.

**Comment by danielthepope** [comment]
We currently use the API to check all Meetup groups in a single request, and it gets back up to 200 events.
This could be fixed by changing the `page=` value to 1 and checking each Meetup group in a separate request.

**Comment by AverageMarcus** [comment]
I'd be concerned about that potentially eating through API request quota. It's a good idea but may need to double check what the limits are if we're hitting this often enough.

**Comment by danielthepope** [comment]
So https://www.meetup.com/meetup_api/#limits suggests the answer is "It depends". The headers from my API request suggest that I'm able to make 30 requests every 10 seconds:
![image](https://user-images.githubusercontent.com/5173183/37036398-7921339e-2147-11e8-9270-3b3e42486646.png)
I think spacing out requests for the 33 groups over an hour will be fine. Just don't make all the requests at once!

**Comment by danielthepope** [comment]
Bah, my reference at #88 didn't close this ticket 😕 Hopefully by 11pm tonight the next STG Reading event will be announced, then we can close this.

**Comment by danielthepope** [comment]
Yep, looks like PR #88 fixed this
