### ISSUE TITLE
Add logging to debug incorrect responses

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/hubot#92]
We've had a few occasions of Dobot responding incorrectly when not actually wanted. It'd be useful to have a log of what was heard (the trigger) and what the response was so we can improve the detection.

**Comment by danielthepope** [comment]
Do you currently have access to the logs when we go `console.log('stuff')`?
(or do we need to come up with something more creative?)

**Comment by AverageMarcus** [comment]
I do yes, Dobot is currently running on my server :)
